import { STORAGE_KEYS, type StorageKey } from "@/lib/storage-keys"

export const MANAGED_LEARNING_STORAGE_KEYS = [
  STORAGE_KEYS.USER_PROFILE,
  STORAGE_KEYS.LESSON_PROGRESS,
  STORAGE_KEYS.ITEM_PROGRESS,
  STORAGE_KEYS.PRACTICE_RESULTS,
  STORAGE_KEYS.SRS_KANA,
  STORAGE_KEYS.SRS_VOCAB,
  STORAGE_KEYS.SRS_MISTAKES,
  STORAGE_KEYS.MISTAKES,
  STORAGE_KEYS.KANA_MASTERED,
  STORAGE_KEYS.KANA_MASTERY_EXCLUDED,
  STORAGE_KEYS.VOCAB_LEARNED,
  STORAGE_KEYS.VOCAB_MASTERY_EXCLUDED,
  STORAGE_KEYS.SPEECH_PREFS,
] as const satisfies readonly StorageKey[]

export type ManagedLearningStorageKey = (typeof MANAGED_LEARNING_STORAGE_KEYS)[number]
