export const PARTICLE_QUESTIONS_EXTRA = [
  {
    sentence: "ひゃくえん＿ありません。",
    full: "ひゃくえんしかありません。",
    answer: "しか",
    options: ["しか", "だけ", "も", "は"],
    explanation: "「しか」必须和否定一起用，表示“仅仅只有”（只有 100 日元）。",
  },
  {
    sentence: "バス＿でんしゃのほうがはやいです。",
    full: "バスよりでんしゃのほうがはやいです。",
    answer: "より",
    options: ["より", "から", "に", "で"],
    explanation: "比较句里，被比较的一方用「より」（电车比巴士快）。",
  },
  {
    sentence: "どようび＿えいがをみます。",
    full: "どようびにえいがをみます。",
    answer: "に",
    options: ["に", "で", "を", "は"],
    explanation: "具体日期/星期几发生的动作，时间点用「に」。",
  },
  {
    sentence: "はし＿ごはんをたべます。",
    full: "はしでごはんをたべます。",
    answer: "で",
    options: ["で", "に", "を", "と"],
    explanation: "使用的工具/手段用「で」（用筷子吃饭）。",
  },
  {
    sentence: "あした せんせい＿あいます。",
    full: "あしたせんせいにあいます。",
    answer: "に",
    options: ["に", "を", "と", "が"],
    explanation: "「あう（见面）」的对象用「に」：せんせいにあう。",
  },
  {
    sentence: "せんせいは「はい」＿いいました。",
    full: "せんせいは「はい」といいました。",
    answer: "と",
    options: ["と", "を", "に", "が"],
    explanation: "引用所说的内容用「と」（说“はい”）。",
  },
  {
    sentence: "パン＿りんごをかいます。",
    full: "パンやりんごをかいます。",
    answer: "や",
    options: ["や", "と", "を", "も"],
    explanation: "不完全列举用「や」（面包、苹果等等）。",
  },
  {
    sentence: "ともだち＿プレゼントをあげます。",
    full: "ともだちにプレゼントをあげます。",
    answer: "に",
    options: ["に", "を", "と", "が"],
    explanation: "给予的对象用「に」（把礼物给朋友）。",
  },
  {
    sentence: "にほんご＿わかります。",
    full: "にほんごがわかります。",
    answer: "が",
    options: ["が", "を", "に", "は"],
    explanation: "「わかる」的对象用「が」（懂日语）。",
  },
  {
    sentence: "かんじ＿できますか。",
    full: "かんじができますか。",
    answer: "が",
    options: ["が", "を", "に", "で"],
    explanation: "「できる」的对象用「が」（会汉字吗）。",
  },
  {
    sentence: "らいねん いしゃ＿なります。",
    full: "らいねんいしゃになります。",
    answer: "に",
    options: ["に", "を", "が", "で"],
    explanation: "变化的结果用「に」（成为医生）。",
  },
  {
    sentence: "ペン＿なまえをかきます。",
    full: "ペンでなまえをかきます。",
    answer: "で",
    options: ["で", "に", "を", "と"],
    explanation: "书写工具也是手段，用「で」（用笔写名字）。",
  },
] as const
