export const PARTICLE_QUESTIONS = [
  {
    sentence: "わたし＿がくせいです。",
    full: "わたしはがくせいです。",
    answer: "は",
    options: ["は", "が", "を", "に"],
    explanation: "「は」标记主题（Topic）。句子在说明“关于我”的信息。",
  },
  {
    sentence: "ねこ＿います。",
    full: "ねこがいます。",
    answer: "が",
    options: ["は", "が", "を", "に"],
    explanation: "「いる/ある」表示“存在”时，常用「が」来引入主语（有什么/谁在）。",
  },
  {
    sentence: "パン＿たべます。",
    full: "パンをたべます。",
    answer: "を",
    options: ["は", "が", "を", "に"],
    explanation: "「を」标记直接宾语（吃“什么”）。",
  },
  {
    sentence: "いえ＿います。",
    full: "いえにいます。",
    answer: "に",
    options: ["に", "で", "を", "が"],
    explanation: "「いる/ある」的“所在地点”用「に」（在哪里“存在/待着”）。",
  },
  {
    sentence: "がっこう＿べんきょうします。",
    full: "がっこうでべんきょうします。",
    answer: "で",
    options: ["に", "で", "を", "と"],
    explanation: "动作发生的场所用「で」（在哪里“做事”）。",
  },
  {
    sentence: "バス＿いきます。",
    full: "バスでいきます。",
    answer: "で",
    options: ["で", "に", "へ", "を"],
    explanation: "交通工具/手段常用「で」（用巴士去）。",
  },
  {
    sentence: "ともだち＿はなします。",
    full: "ともだちとはなします。",
    answer: "と",
    options: ["と", "へ", "で", "を"],
    explanation: "和谁一起做（对话对象）常用「と」（和朋友说话）。",
  },
  {
    sentence: "わたしはすし＿すきです。",
    full: "わたしはすしがすきです。",
    answer: "が",
    options: ["が", "を", "に", "で"],
    explanation: "「すき/きらい/ほしい」常用「が」标记对象（喜欢“什么”）。",
  },
  {
    sentence: "8じ＿おきます。",
    full: "8じにおきます。",
    answer: "に",
    options: ["に", "で", "を", "が"],
    explanation: "具体时间点常用「に」（在8点起床）。",
  },
  {
    sentence: "きょう＿さむいです。",
    full: "きょうはさむいです。",
    answer: "は",
    options: ["は", "が", "を", "に"],
    explanation: "时间作为话题时常用「は」（今天“就…而言”很冷）。",
  },
  {
    sentence: "ともだちはいきます。わたし＿いきます。",
    full: "ともだちはいきます。わたしもいきます。",
    answer: "も",
    options: ["も", "は", "を", "に"],
    explanation: "前一句已经说了“朋友去”，“我也去”用「も」表示同样。",
  },
  {
    sentence: "とうきょう＿いきます。",
    full: "とうきょうへいきます。",
    answer: "へ",
    options: ["へ", "を", "で", "と"],
    explanation: "「へ」表示移动的方向（往东京去）。",
  },
  {
    sentence: "これ＿なんですか。",
    full: "これはなんですか。",
    answer: "は",
    options: ["は", "を", "に", "で"],
    explanation: "问“这是什么”时，「これは」把“这个”立为话题。",
  },
  {
    sentence: "みず＿のみます。",
    full: "みずをのみます。",
    answer: "を",
    options: ["を", "が", "に", "で"],
    explanation: "「を」标记“喝”的直接对象（喝水）。",
  },
  {
    sentence: "としょかん＿ほんをよみます。",
    full: "としょかんでほんをよみます。",
    answer: "で",
    options: ["で", "に", "を", "へ"],
    explanation: "在图书馆“做”读书这个动作，动作场所用「で」。",
  },
  {
    sentence: "まいあさ 7じ＿おきます。",
    full: "まいあさ7じにおきます。",
    answer: "に",
    options: ["に", "で", "を", "が"],
    explanation: "具体时刻（7点）用「に」。",
  },
  {
    sentence: "これは わたし＿かさです。",
    full: "これはわたしのかさです。",
    answer: "の",
    options: ["の", "は", "が", "を"],
    explanation: "「の」表示所属：我的伞。",
  },
  {
    sentence: "えき＿いえまであるきます。",
    full: "えきからいえまであるきます。",
    answer: "から",
    options: ["から", "まで", "を", "に"],
    explanation: "起点用「から」（从车站），终点用「まで」（到家）。",
  },
  {
    sentence: "9じから 5じ＿はたらきます。",
    full: "9じから5じまではたらきます。",
    answer: "まで",
    options: ["まで", "から", "に", "を"],
    explanation: "时间/空间的终点用「まで」（工作到五点）。",
  },
  {
    sentence: "スーパー＿くだものをかいます。",
    full: "スーパーでくだものをかいます。",
    answer: "で",
    options: ["で", "に", "が", "へ"],
    explanation: "“买东西”这个动作发生的场所用「で」。",
  },
  {
    sentence: "ともだち＿えいがをみます。",
    full: "ともだちとえいがをみます。",
    answer: "と",
    options: ["と", "を", "に", "へ"],
    explanation: "「と」表示“和某人一起”做某事。",
  },
  {
    sentence: "わたしはせんせい＿しつもんします。",
    full: "わたしはせんせいにしつもんします。",
    answer: "に",
    options: ["に", "を", "が", "は"],
    explanation: "提问、打电话等动作的对象用「に」（向老师提问）。",
  },
  {
    sentence: "へや＿ねこがいます。",
    full: "へやにねこがいます。",
    answer: "に",
    options: ["に", "で", "を", "と"],
    explanation: "存在（いる/ある）的场所用「に」（房间里有猫）。",
  },
  {
    sentence: "こうえん＿さんぽします。",
    full: "こうえんをさんぽします。",
    answer: "を",
    options: ["を", "に", "と", "が"],
    explanation: "在场所里“移动经过”（散步/飞过/通过）用「を」。",
  },
  {
    sentence: "りんご＿みっつください。",
    full: "りんごをみっつください。",
    answer: "を",
    options: ["を", "が", "で", "の"],
    explanation: "请求给某物用「を」：りんごをください。",
  },
  {
    sentence: "バナナ＿りんごをかいます。",
    full: "バナナとりんごをかいます。",
    answer: "と",
    options: ["と", "を", "も", "は"],
    explanation: "并列两个名词用「と」（香蕉“和”苹果）。",
  },
  {
    sentence: "わたしはコーヒー＿すきです。",
    full: "わたしはコーヒーがすきです。",
    answer: "が",
    options: ["が", "を", "に", "で"],
    explanation: "「すき/きらい/じょうず」的对象用「が」。",
  },
  {
    sentence: "あした おおさか＿いきます。",
    full: "あしたおおさかにいきます。",
    answer: "に",
    options: ["に", "を", "で", "が"],
    explanation: "移动的目的地用「に」（也可以用「へ」）。",
  },
  {
    sentence: "だれ＿きましたか。",
    full: "だれがきましたか。",
    answer: "が",
    options: ["が", "は", "を", "に"],
    explanation: "疑问词（だれ/なに）做主语时用「が」，不用「は」。",
  },
  {
    sentence: "なんじ＿ねますか。",
    full: "なんじにねますか。",
    answer: "に",
    options: ["に", "で", "を", "が"],
    explanation: "询问具体时刻的动作时间，用「に」。",
  },
  {
    sentence: "うち＿テレビをみます。",
    full: "うちでテレビをみます。",
    answer: "で",
    options: ["で", "に", "を", "が"],
    explanation: "在家里“做”看电视这个动作，动作场所用「で」。",
  },
  {
    sentence: "ふゆ＿さむいです。",
    full: "ふゆはさむいです。",
    answer: "は",
    options: ["は", "を", "に", "の"],
    explanation: "把“冬天”立为话题来说明性质，用「は」。",
  },
  {
    sentence: "つくえのうえに ほん＿あります。",
    full: "つくえのうえにほんがあります。",
    answer: "が",
    options: ["が", "を", "に", "で"],
    explanation: "描述存在“有什么”时用「が」（桌上有书）。",
  },
  {
    sentence: "きのう ともだち＿あいました。",
    full: "きのうともだちにあいました。",
    answer: "に",
    options: ["に", "を", "が", "は"],
    explanation: "「あう（见面）」的对象用「に」：ともだちにあう。",
  },
  {
    sentence: "コンビニ＿おにぎりをかいます。",
    full: "コンビニでおにぎりをかいます。",
    answer: "で",
    options: ["で", "に", "が", "へ"],
    explanation: "“买”的动作发生在便利店，动作场所用「で」。",
  },
] as const
