import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import test from "node:test"

const root = path.resolve(import.meta.dirname, "..", "..")

function read(relPath) {
  return fs.readFileSync(path.join(root, relPath), "utf8")
}

test("home page keeps profile persistence in the settings dialog", () => {
  const route = read("src/app/page.tsx")
  const page = read("src/components/home/home-page.tsx")
  const nowPlaying = read("src/components/home/home-now-playing.tsx")

  assert.doesNotMatch(route, /"use client"/)
  assert.match(route, /from "@\/components\/home\/home-page"/)
  assert.match(route, /<HomePage \/>/)
  assert.match(page, /from "@\/components\/home\/home-now-playing"/)
  assert.match(nowPlaying, /from "@\/components\/home\/onboarding-panel"/)
  assert.match(nowPlaying, /from "@\/components\/practice\/practice-save-error"/)
  assert.match(page, /from "@\/lib\/home-page-model"/)
  assert.match(page, /from "@\/lib\/learning-recommendation"/)
  assert.match(page, /useLearningRecommendation\(\)/)
  assert.match(page, /buildHomePageModel\(/)
  assert.match(page, /skill: recommendedSkill/)
  assert.match(page, /mistakeIds: mistakes\.byId\.keys\(\)/)
  assert.match(page, /const \[profileSaveError, setProfileSaveError\] = useState\(false\)/)
  assert.match(page, /const saved = await runLearningWrite\(\(\) => saveProfile\(input\)\)/)
  assert.match(page, /setProfileSaveError\(!saved\)/)
  assert.match(nowPlaying, /<PracticeSaveError show=\{profileSaveError\} \/>/)
  assert.doesNotMatch(page, /STARTER_LESSONS\.slice/)
  assert.doesNotMatch(page, /getLessonEntryStatus\(lesson/)
  assert.doesNotMatch(page, /dueMistakeIds = useMemo/)
  assert.doesNotMatch(page, /Object\.values\(learning\.items\)/)
  assert.doesNotMatch(page, /useLearningProgress/)
  assert.doesNotMatch(page, /useLearningStatus/)
  assert.doesNotMatch(page, /useKanaProgress/)
  assert.doesNotMatch(page, /useVocabProgress/)
  assert.doesNotMatch(page, /getKanaSkillStats\(kanaData/)
  assert.doesNotMatch(page, /summarizeLearnedVocabIds/)
  assert.doesNotMatch(page, /getRecommendedSkillId\(kanaStats, vocabStats\)/)
  assert.doesNotMatch(page, /const goalOptions/)
  assert.doesNotMatch(page, /const kanaOptions/)
  assert.doesNotMatch(page, /const romajiOptions/)
  assert.doesNotMatch(page, /function SelectPills/)
  assert.doesNotMatch(page, /type UserProfile/)
})

test("home hero images use bounded responsive sizes for LCP", () => {
  const page = read("src/components/home/home-page.tsx")
  const nowPlaying = read("src/components/home/home-now-playing.tsx")

  assert.doesNotMatch(page, /sizes="100vw"/)
  assert.doesNotMatch(nowPlaying, /sizes="100vw"/)
  assert.match(read("src/components/home/home-scene.tsx"), /data-testid="home-start-learning"/)
  assert.match(nowPlaying, /label="课程"/)
  assert.match(nowPlaying, /label="入门词"/)
  assert.match(nowPlaying, /data-testid="home-edit-profile"/)
  assert.match(nowPlaying, /data-testid="home-edit-profile-cancel"/)
  assert.match(page, /survivalDone=\{survivalDone\}/)
  assert.match(page, /href=\{weakestHref\}/)
})

test("home scene keeps real learning data and accessible controls independent of decorative artwork", () => {
  const page = read("src/components/home/home-page.tsx")
  const scene = read("src/components/home/home-scene.tsx")
  assert.match(page, /<HomeScene/)
  assert.match(page, /entry=\{learningEntry\}/)
  assert.match(scene, /aria-labelledby="home-cover-title"/)
  assert.match(scene, /aria-hidden="true"/)
  assert.match(scene, /megumi-manga\.webp" alt="" fill sizes=/)
  assert.doesNotMatch(scene, /sizes="100vw"/)
  assert.match(scene, /loading="eager" fetchPriority="high"/)
  assert.match(scene, /\{entry\.title\}/)
  assert.match(scene, /href=\{entry\.href\}/)
  const progress = read("src/components/home/home-now-playing.tsx")
  assert.match(progress, /role="progressbar" aria-label="今日练习进度"/)
  assert.match(progress, /aria-valuenow=\{Math\.min\(todayPracticeCount, dailyTarget\)\}/)
})

test("OnboardingPanel owns profile option state and save payload", () => {
  const source = read("src/components/home/onboarding-panel.tsx")

  assert.match(source, /export function OnboardingPanel/)
  assert.match(source, /onSave: \(input: Omit<UserProfile, "createdAt" \| "updatedAt">\) => Promise<boolean>/)
  assert.match(source, /const goalOptions/)
  assert.match(source, /const kanaOptions/)
  assert.match(source, /const romajiOptions/)
  assert.match(source, /useState<LearningGoal>\(initial\?\.goal \?\? "balanced"\)/)
  assert.match(source, /useState<KanaLevel>\(initial\?\.kanaLevel \?\? "none"\)/)
  assert.match(source, /useState<RomajiMode>\(initial\?\.romajiMode \?\? "practice"\)/)
  assert.match(source, /useState\(initial\?\.minutesPerDay \?\? 10\)/)
  assert.match(source, /aria-pressed=\{goal === item\.value\}/)
  assert.match(source, /aria-pressed=\{value === item\.value\}/)
  assert.match(source, /aria-label="每天学习时长"/)
  assert.match(source, /data-testid=\{`onboarding-goal-\$\{item\.value\}`\}/)
  assert.match(source, /data-testid=\{`onboarding-\$\{item\.value\}`\}/)
  assert.match(source, /data-testid="onboarding-minutes"/)
  assert.match(source, /data-testid="onboarding-save"/)
  assert.match(source, /onSave\(\{ goal, kanaLevel, romajiMode, minutesPerDay \}\)/)
  assert.match(source, /function SelectPills/)
  assert.match(source, /保存并开始学习/)
  assert.match(source, /保存学习设置/)
})
