import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import test from "node:test"

const root = path.resolve(import.meta.dirname, "..", "..")

function read(relPath) {
  return fs.readFileSync(path.join(root, relPath), "utf8")
}

test("home page delegates first-run profile setup to OnboardingPanel", () => {
  const route = read("src/app/page.tsx")
  const page = read("src/components/home/home-page.tsx")
  const nowPlaying = read("src/components/home/home-now-playing.tsx")

  assert.doesNotMatch(route, /"use client"/)
  assert.match(route, /from "@\/components\/home\/home-page"/)
  assert.match(route, /<HomePage \/>/)
  assert.match(page, /from "@\/components\/home\/home-now-playing"/)
  assert.match(page, /from "@\/components\/home\/home-starter-lessons"/)
  assert.match(nowPlaying, /from "@\/components\/home\/onboarding-panel"/)
  assert.match(nowPlaying, /from "@\/components\/practice\/practice-save-error"/)
  assert.match(page, /from "@\/lib\/home-page-model"/)
  assert.match(page, /from "@\/lib\/learning-recommendation"/)
  assert.match(page, /useLearningRecommendation\(\)/)
  assert.match(page, /buildHomePageModel\(/)
  assert.match(page, /skill: recommendedSkill/)
  assert.match(page, /mistakeIds: mistakes\.byId\.keys\(\)/)
  assert.match(page, /const \[profileSaveError, setProfileSaveError\] = useState\(false\)/)
  assert.match(page, /const saved = saveProfile\(input\)/)
  assert.match(page, /setProfileSaveError\(!saved\)/)
  assert.match(page, /<HomeStarterLessons completedLessonIds=\{learning\.completedLessonIds\} activeLessonId=\{nextLesson\?\.id\} \/>/)
  assert.match(nowPlaying, /<PracticeSaveError show=\{profileSaveError\} \/>/)
  assert.doesNotMatch(page, /STARTER_LESSONS\.slice/)
  assert.doesNotMatch(page, /getLessonEntryStatus\(lesson/)
  assert.doesNotMatch(page, /dueMistakeIds = useMemo/)
  assert.doesNotMatch(page, /Object\.values\(learning\.items\)/)
  assert.doesNotMatch(page, /useLearningProgress/)
  assert.doesNotMatch(page, /useLearningStatus/)
  assert.doesNotMatch(page, /useKanaProgress/)
  assert.doesNotMatch(page, /useVocabProgress/)
  assert.doesNotMatch(page, /getKanaSkillStats\(kanaData/)
  assert.doesNotMatch(page, /summarizeLearnedVocabIds/)
  assert.doesNotMatch(page, /getRecommendedSkillId\(kanaStats, vocabStats\)/)
  assert.doesNotMatch(page, /const goalOptions/)
  assert.doesNotMatch(page, /const kanaOptions/)
  assert.doesNotMatch(page, /const romajiOptions/)
  assert.doesNotMatch(page, /function SelectPills/)
  assert.doesNotMatch(page, /type UserProfile/)
})

test("home hero images use bounded responsive sizes for LCP", () => {
  const page = read("src/components/home/home-page.tsx")
  const nowPlaying = read("src/components/home/home-now-playing.tsx")

  assert.doesNotMatch(page, /sizes="100vw"/)
  assert.doesNotMatch(nowPlaying, /sizes="100vw"/)
  assert.match(nowPlaying, /data-testid="home-start-learning"/)
  assert.match(nowPlaying, /font-jp/)
  assert.match(nowPlaying, /label="课表"/)
  assert.match(nowPlaying, /label="生存词"/)
  assert.match(nowPlaying, /data-testid="home-edit-profile"/)
  assert.match(nowPlaying, /data-testid="home-edit-profile-cancel"/)
  assert.match(page, /survivalDone=\{survivalDone\}/)
  assert.match(page, /href=\{weakestHref\}/)
})

test("home cover art preserves its sheet ratio and fits short viewports", () => {
  const page = read("src/components/home/home-page.tsx")
  const styles = read("src/app/globals.css")

  assert.match(page, /className="mx-auto flex min-w-0 w-full max-w-4xl flex-col items-center"/)
  assert.match(styles, /\.cover-art\s*\{[\s\S]*?aspect-ratio:\s*4\s*\/\s*3;/)
  assert.match(styles, /\.cover-art\s*\{[\s\S]*?max-width:\s*100%;/)
  assert.match(styles, /calc\(112svh - 18rem\)/)
  assert.match(styles, /@media \(max-height: 640px\)[\s\S]*?\.paper-cover \{[\s\S]*?margin-top: 0;/)
  assert.match(styles, /@media \(max-height: 560px\)[\s\S]*?\.cover-scroll \{ display: none; \}/)
  assert.match(styles, /@media \(max-height: 420px\)[\s\S]*?\.paper-cover \{[\s\S]*?height: auto;[\s\S]*?padding-block: 1rem;/)
  assert.match(styles, /width: min\(62vmin, 190px, 100%\)/)
})

test("HomeStarterLessons owns starter lesson cards and locked card behavior", () => {
  const source = read("src/components/home/home-starter-lessons.tsx")

  assert.match(source, /export function HomeStarterLessons/)
  assert.match(source, /completedLessonIds: ReadonlySet<string>/)
  assert.match(source, /activeLessonId: string \| null \| undefined/)
  assert.match(source, /STARTER_LESSONS\.map\(/)
  assert.match(source, /getLessonEntryStatus\(lesson, completedLessonIds, activeLessonId, kanaLevel\)/)
  assert.match(source, /getLessonEntryBadge\(status\)/)
  assert.match(source, /if \(locked\)/)
  assert.match(source, /aria-disabled="true"/)
  assert.match(source, /href=\{`\/learn\/\$\{lesson\.id\}`\}/)
})

test("OnboardingPanel owns profile option state and save payload", () => {
  const source = read("src/components/home/onboarding-panel.tsx")

  assert.match(source, /export function OnboardingPanel/)
  assert.match(source, /onSave: \(input: Omit<UserProfile, "createdAt" \| "updatedAt">\) => boolean/)
  assert.match(source, /const goalOptions/)
  assert.match(source, /const kanaOptions/)
  assert.match(source, /const romajiOptions/)
  assert.match(source, /useState<LearningGoal>\(initial\?\.goal \?\? "balanced"\)/)
  assert.match(source, /useState<KanaLevel>\(initial\?\.kanaLevel \?\? "none"\)/)
  assert.match(source, /useState<RomajiMode>\(initial\?\.romajiMode \?\? "practice"\)/)
  assert.match(source, /useState\(initial\?\.minutesPerDay \?\? 10\)/)
  assert.match(source, /aria-pressed=\{goal === item\.value\}/)
  assert.match(source, /aria-pressed=\{value === item\.value\}/)
  assert.match(source, /aria-label="每天学习时长"/)
  assert.match(source, /data-testid=\{`onboarding-goal-\$\{item\.value\}`\}/)
  assert.match(source, /data-testid=\{`onboarding-\$\{item\.value\}`\}/)
  assert.match(source, /data-testid="onboarding-minutes"/)
  assert.match(source, /data-testid="onboarding-save"/)
  assert.match(source, /onSave\(\{ goal, kanaLevel, romajiMode, minutesPerDay \}\)/)
  assert.match(source, /function SelectPills/)
  assert.match(source, /生成今日计划/)
  assert.match(source, /保存学习设置/)
})
