import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import test from "node:test"

const root = path.resolve(import.meta.dirname, "..", "..")

function read(relPath) {
  return fs.readFileSync(path.join(root, relPath), "utf8")
}

test("review page exposes local learning data management through the shared store facade", () => {
  const dashboard = read("src/components/review/review-dashboard.tsx")
  const panel = read("src/components/review/learning-data-panel.tsx")

  assert.match(dashboard, /<LearningDataPanel \/>/)
  assert.match(panel, /tryCreateLearningBackup/)
  assert.match(panel, /parseLearningBackup/)
  assert.match(panel, /restoreLearningBackup/)
  assert.match(panel, /resetLearningData/)
  assert.match(panel, /ConfirmActionDialog/)
  assert.match(panel, /function backupFileName/)
  assert.match(panel, /slice\(0, 19\)\.replace\(\/:\/g, "-"\)\.replace\("T", "-"\)/)
  assert.match(panel, /document\.body\.appendChild\(anchor\)/)
  assert.match(panel, /anchor\?\.remove\(\)/)
  assert.match(panel, /URL\.revokeObjectURL\(url\)/)
  assert.match(panel, /无法读取本地学习数据，导出失败。/)
  assert.match(panel, /备份文件生成失败。/)
  assert.match(panel, /const importData = React\.useCallback/)
  assert.match(panel, /LEARNING_BACKUP_FILE_MAX_BYTES = 2 \* 1024 \* 1024/)
  assert.match(panel, /file\.size > LEARNING_BACKUP_FILE_MAX_BYTES/)
  assert.match(panel, /备份文件超过 2 MB，无法导入。/)
  assert.match(panel, /const reader = new FileReader\(\)/)
  assert.match(panel, /try \{\s*reader\.readAsText\(file\)\s*\} catch \{/)
  assert.match(panel, /reader\.onerror = \(\) => setNotice\(\{ tone: "error", text: "备份文件无法读取。" \}\)/)
  assert.match(panel, /reader\.onabort = \(\) => setNotice\(\{ tone: "error", text: "备份文件读取已取消。" \}\)/)
  assert.match(panel, /const \[pendingBackup, setPendingBackup\] = React\.useState<LearningBackup \| null>\(null\)/)
  assert.match(panel, /setPendingBackup\(backup\)/)
  assert.match(panel, /const restorePendingBackup = React\.useCallback/)
  assert.match(panel, /restoreLearningBackup\(pendingBackup\)/)
  assert.match(panel, /function backupRestoreDescription/)
  assert.match(panel, /该备份不含学习数据/)
  assert.match(panel, /包含 \$\{entryCount\} 类本地数据/)
  assert.match(panel, /title="恢复学习数据"/)
  assert.match(panel, /backupRestoreDescription\(pendingBackup\)/)
  assert.match(panel, /testId="learning-data-restore-dialog"/)
  assert.match(panel, /onCancel=\{\(\) => setPendingBackup\(null\)\}/)
  assert.match(panel, /onConfirm=\{restorePendingBackup\}/)
  assert.match(panel, /const \[resetDialogOpen, setResetDialogOpen\] = React\.useState\(false\)/)
  assert.match(panel, /aria-label="清空本地学习数据"/)
  assert.match(panel, /open=\{resetDialogOpen\}/)
  assert.match(panel, /title="清空本地学习数据"/)
  assert.match(panel, /description="这会删除当前浏览器里的进度、SRS、错题本和朗读偏好。导出的备份文件不会受到影响。"/)
  assert.match(panel, /testId="learning-data-reset-dialog"/)
  assert.match(panel, /onCancel=\{\(\) => setResetDialogOpen\(false\)\}/)
  assert.match(panel, /onConfirm=\{resetData\}/)
  assert.doesNotMatch(panel, /localStorage\./)
  assert.match(panel, /data-testid="learning-data-panel"/)
  assert.match(panel, /data-testid="learning-data-export"/)
  assert.match(panel, /data-testid="learning-data-import"/)
  assert.match(panel, /data-testid="learning-data-reset"/)
  assert.match(panel, /data-testid="learning-data-notice"/)
  assert.match(panel, /role=\{notice\.tone === "error" \? "alert" : "status"\}/)
  assert.match(panel, /aria-live="polite"/)
  assert.match(panel, /data-tone=\{notice\.tone\}/)
})
