import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import test from "node:test"

const root = path.resolve(import.meta.dirname, "..", "..")
const sw = fs.readFileSync(path.join(root, "public/sw.js"), "utf8")
const layout = fs.readFileSync(path.join(root, "src/app/layout.tsx"), "utf8")
const register = fs.readFileSync(path.join(root, "src/components/pwa-register.tsx"), "utf8")
const pwaE2e = fs.readFileSync(path.join(root, "tests/e2e/pwa-offline.mjs"), "utf8")
const harness = fs.readFileSync(path.join(root, "tests/e2e/harness.mjs"), "utf8")
const webPackage = fs.readFileSync(path.join(root, "package.json"), "utf8")

test("PWA registers a production service worker and exposes install metadata", () => {
  assert.match(layout, /manifest:\s*"\/manifest\.webmanifest"/)
  assert.match(layout, /appleWebApp:\s*\{/)
  assert.match(layout, /themeColor:\s*"#ffb7b2"/)
  assert.match(register, /process\.env\.NODE_ENV !== "production"/)
  assert.match(register, /navigator\.serviceWorker\.register\("\/sw\.js"\)/)
})

test("service worker caches static assets and visited navigation pages without learning state", () => {
  assert.match(sw, /const STATIC_CACHE_NAME = "yasashi-static-v\d+"/)
  assert.match(sw, /const NAVIGATION_CACHE_NAME = "yasashi-navigation-v\d+"/)
  assert.match(sw, /const OFFLINE_FALLBACK_URL = "\/offline\.html"/)
  assert.match(sw, /\/brand\/logo-mark\.svg/)
  assert.match(sw, /\/brand\/logo-wordmark\.svg/)
  assert.match(sw, /\/assets\/kana\/kana-seion\.webp/)
  assert.match(sw, /\/assets\/kana\/kana-all@2x\.webp/)
  assert.match(sw, /\/assets\/textures\/paper-washi-tile\.png/)
  assert.match(sw, /\/assets\/vocab-categories\/greetings\.webp/)
  assert.match(sw, /const requestUrl = new URL\(request\.url\)/)
  assert.match(sw, /requestUrl\.origin !== self\.location\.origin/)
  assert.match(sw, /request\.method !== "GET"/)
  assert.match(sw, /request\.mode === "navigate"/)
  assert.match(sw, /networkFirstNavigation\(request\)/)
  assert.match(sw, /cache\.put\(request, response\.clone\(\)\)/)
  assert.match(sw, /cache\.match\(request\)/)
  assert.match(sw, /const staticCached = await caches\.match\(request\)/)
  assert.match(sw, /if \(staticCached\) return staticCached/)
  assert.match(sw, /caches\.match\(OFFLINE_FALLBACK_URL\)/)
  assert.match(sw, /cacheFirstStaticAsset\(request, requestUrl\)/)
  assert.match(sw, /request\.destination === "image"/)
  assert.match(sw, /request\.destination === "style"/)
  assert.match(sw, /request\.destination === "script"/)
  assert.match(sw, /requestUrl\.pathname\.startsWith\("\/animcjk\/"\)/)
  assert.match(sw, /requestUrl\.pathname\.endsWith\("\.svg"\)/)
  assert.doesNotMatch(sw, /localStorage/)
  assert.doesNotMatch(sw, /yasashi\.learning/)
  assert.doesNotMatch(sw, /yasashi\.srs/)
  assert.doesNotMatch(sw, /yasashi\.mistakes/)
})

test("PWA offline E2E verifies visited-page cache, fallback, and local state preservation", () => {
  assert.match(webPackage, /"e2e:pwa": "node tests\/e2e\/pwa-offline\.mjs"/)
  assert.match(webPackage, /"e2e:pwa:required": "node tests\/e2e\/pwa-offline\.mjs --required"/)
  assert.match(pwaE2e, /isE2ERequired\("E2E_PWA_REQUIRED"\)/)
  assert.match(pwaE2e, /importPlaywrightOrSkip/)
  assert.match(pwaE2e, /skipOptionalPlaywrightRuntimeError/)
  assert.match(harness, /process\.argv\.includes\("--required"\)/)
  assert.match(harness, /process\.env\[envName\] === "1"/)
  assert.match(pwaE2e, /PWA E2E skipped: Playwright is not installed/)
  assert.match(pwaE2e, /PWA E2E skipped: Playwright browser binaries are not installed/)
  assert.match(webPackage, /"e2e:install": "playwright install chromium"/)
  assert.match(harness, /npmCommand\(\), \["run", "build"\]/)
  assert.match(harness, /npmCommand\(\), \["run", "start"/)
  assert.match(pwaE2e, /navigator\.serviceWorker\.ready/)
  assert.match(pwaE2e, /context\.setOffline\(true\)/)
  assert.match(pwaE2e, /\/learn\/day-1-a-row-hello/)
  assert.match(pwaE2e, /lesson-next/)
  assert.match(pwaE2e, /offline navigation cache should serve a visited lesson page/)
  assert.match(pwaE2e, /\/animcjk\/kana\/12354\.svg/)
  assert.match(pwaE2e, /AnimCJK SVG should load online before offline cache verification/)
  assert.match(pwaE2e, /home-start-learning/)
  assert.match(pwaE2e, /offline static cache should serve the app home page/)
  assert.match(pwaE2e, /offline cache should serve a visited AnimCJK SVG/)
  assert.match(pwaE2e, /offline AnimCJK response should remain an SVG/)
  assert.match(pwaE2e, /page\.goto\(`\$\{baseUrl\}\/offline-smoke-/)
  assert.match(pwaE2e, /navigation failures should render the offline fallback/)
  assert.match(pwaE2e, /yasashi\.learning\.lessons\.v1/)
  assert.match(pwaE2e, /offline fallback must not overwrite local learning state/)
})
