import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import test from "node:test"

const root = path.resolve(import.meta.dirname, "..", "..")

function read(relPath) {
  return fs.readFileSync(path.join(root, relPath), "utf8")
}

test("review page delegates dashboard surfaces while keeping SRS/session wiring", () => {
  const route = read("src/app/review/page.tsx")
  const page = read("src/components/review/review-page.tsx")

  assert.doesNotMatch(route, /"use client"/)
  assert.match(route, /from "@\/components\/review\/review-page"/)
  assert.match(route, /<ReviewPage \/>/)
  assert.match(page, /import dynamic from "next\/dynamic"/)
  assert.match(page, /from "@\/components\/review\/review-dashboard"/)
  assert.doesNotMatch(page, /import \{ ReviewRunner/)
  assert.match(page, /from "@\/lib\/review-session"/)
  assert.match(page, /from "@\/lib\/review-dashboard-model"/)
  assert.match(page, /from "@\/lib\/learning-status"/)
  assert.match(page, /from "@\/lib\/learning-store"/)
  assert.match(page, /const ReviewRunner = dynamic\(/)
  assert.match(page, /import\("@\/components\/review\/review-runner"\)/)
  assert.match(page, /ssr: false/)
  assert.match(page, /const learning = useLearningStatus\(\)/)
  assert.match(page, /<ReviewDashboard\b/)
  assert.match(page, /buildReviewDashboardModel/)
  assert.match(page, /const dashboard = useMemo/)
  assert.match(page, /masteredIds: learning\.masteredKanaIds/)
  assert.match(page, /learnedIds: learning\.learnedVocabIds/)
  assert.match(page, /mistakeIds: mistakes\.byId\.keys\(\)/)
  assert.match(page, /mistakeItems: mistakes\.list/)
  assert.match(page, /mistakeKindDueLabel=\{dashboard\.mistakeKindDueLabel\}/)
  assert.match(page, /const \[reviewSaveError, setReviewSaveError\] = useState\(false\)/)
  assert.match(page, /learning\.loaded && mistakes\.loaded && kanaSrs\.loaded && vocabSrs\.loaded && mistakeSrs\.loaded/)
  assert.match(page, /if \(!loaded\)/)
  assert.match(page, /role="status"/)
  assert.match(page, /正在加载复习/)
  assert.match(page, /const startSession = \(nextSession: ReviewSession\) => \{/)
  assert.match(page, /setReviewSaveError\(false\)/)
  assert.match(page, /runLearningStorageTransaction\(\(\) => enrollMissingReviewItems\(dashboard\.kanaEnrollMissing, kanaSrs\.enroll\)\)/)
  assert.match(page, /runLearningStorageTransaction\(\(\) => enrollMissingReviewItems\(dashboard\.vocabEnrollMissing, vocabSrs\.enroll\)\)/)
  assert.match(page, /runLearningStorageTransaction\(\(\) => enrollMissingReviewItems\(dashboard\.mistakeEnrollMissing, mistakeSrs\.enroll\)\)/)
  assert.doesNotMatch(page, /mistakeSrs\.grade\(id, "again"\)/)
  assert.match(page, /const removeMistake = \(id: string\) => setReviewSaveError\(!mistakes\.remove\(id\)\)/)
  assert.match(page, /const clearMistakes = \(\) => setReviewSaveError\(!mistakes\.clear\(\)\)/)
  assert.match(page, /deck: "today",\s+items: dashboard\.todayQueue,\s+remainingDueAfterBatch: Math\.max\(0, dashboard\.totalDue - dashboard\.todayQueue\.length\),/)
  assert.match(page, /startSession\(\{ deck: "kana", ids: dashboard\.reviewableKanaDueIds \}\)/)
  assert.match(page, /startSession\(\{ deck: "vocab", ids: dashboard\.vocabDueIds \}\)/)
  assert.match(page, /startSession\(\{ deck: "mistakes", ids: dashboard\.dueMistakeIds \}\)/)
  assert.match(page, /onEnrollMissing: enrollKanaMissing/)
  assert.match(page, /onEnrollMissing: enrollVocabMissing/)
  assert.match(page, /onEnrollMissing: enrollMistakeMissing/)
  assert.doesNotMatch(page, /useKanaProgress/)
  assert.doesNotMatch(page, /useVocabProgress/)
  assert.doesNotMatch(page, /buildTodayReviewQueue/)
  assert.doesNotMatch(page, /isReviewableKanaId/)
  assert.doesNotMatch(page, /getNextSrsDueAt/)
  assert.doesNotMatch(page, /function DeckCard/)
  assert.doesNotMatch(page, /state-empty\.webp/)
  assert.doesNotMatch(page, /review-streak\.webp/)
  assert.doesNotMatch(page, /SpeechSettingsBar/)
  assert.doesNotMatch(page, /LearningDataPanel/)
})

test("ReviewDashboard owns review landing UI and delegates formatting to pure model helpers", () => {
  const source = read("src/components/review/review-dashboard.tsx")

  assert.match(source, /export function ReviewDashboard/)
  assert.match(source, /useState/)
  assert.match(source, /from "@\/components\/ui\/confirm-action-dialog"/)
  assert.match(source, /from "@\/lib\/review-dashboard-model"/)
  assert.match(source, /formatReviewNextDueAt/)
  assert.match(source, /from "@\/components\/review\/review-banners"/)
  assert.match(source, /<FirstReviewBanner/)
  assert.match(source, /<ReviewStreakBanner/)
  assert.match(source, /<TodayReviewPanel/)
  assert.match(source, /到期 \{mistakeKindDueLabel\}/)
  assert.match(source, /data-testid="mistakes-clear"/)
  assert.match(source, /from "@\/components\/review\/review-deck-card"/)
  assert.match(source, /from "@\/components\/review\/recent-mistakes"/)
  assert.match(source, /from "@\/components\/practice\/practice-save-error"/)
  assert.match(source, /<ReviewDeckCard\b/)
  assert.match(source, /<RecentMistakes\b/)
  assert.match(source, /saveError: boolean/)
  assert.match(source, /enrollMissing: number/)
  assert.match(source, /onEnrollMissing: \(\) => void/)
  assert.match(source, /<PracticeSaveError show=\{mistakes\.saveError\} \/>/)
  assert.match(source, /const \[confirmClearMistakesOpen, setConfirmClearMistakesOpen\] = useState\(false\)/)
  assert.match(source, /const requestClearMistakes = \(\) => setConfirmClearMistakesOpen\(true\)/)
  assert.match(source, /const confirmClearMistakes = \(\) => \{[\s\S]*setConfirmClearMistakesOpen\(false\)[\s\S]*mistakes\.onClear\(\)[\s\S]*\}/)
  assert.match(source, /onClick=\{requestClearMistakes\}/)
  assert.doesNotMatch(source, /onClick=\{mistakes\.onClear\}/)
  assert.match(source, /<ConfirmActionDialog/)
  assert.match(source, /testId="mistakes-clear-dialog"/)
  assert.match(source, /startTestId="review-start-mistakes"/)
  assert.match(source, /mistakes\.enrollMissing > 0/)
  assert.match(source, /mistakes\.onEnrollMissing/)
  assert.doesNotMatch(source, /function ReviewDeckCard/)
  assert.doesNotMatch(source, /function RecentMistakes/)
  assert.match(source, /SpeechSettingsBar/)
  assert.match(source, /LearningDataPanel/)
  assert.doesNotMatch(source, /state-empty\.webp/)
  assert.doesNotMatch(source, /review-streak\.webp/)
  assert.doesNotMatch(source, /data-testid="review-start-today"/)
})

test("review banners own first-time, streak, and today review surfaces", () => {
  const source = read("src/components/review/review-banners.tsx")

  assert.match(source, /export function FirstReviewBanner/)
  assert.match(source, /export function ReviewStreakBanner/)
  assert.match(source, /export function TodayReviewPanel/)
  assert.match(source, /state-empty\.webp/)
  assert.match(source, /review-streak\.webp/)
  assert.match(source, /href="\/kana"/)
  assert.match(source, /href="\/vocabulary"/)
  assert.match(source, /href="\/quiz"/)
  assert.match(source, /href="\/path"/)
  assert.match(source, /data-testid="review-empty-state"/)
  assert.match(source, /"review-due-state"/)
  assert.match(source, /"review-scheduled-empty-state"/)
  assert.match(source, /todayQueueLength \? "review-today-due" : "review-today-empty"/)
  assert.match(source, /data-testid="review-start-today"/)
  assert.match(source, /错题 \{counts\.mistakesDue\} · 假名 \{counts\.kanaDue\} · 单词 \{counts\.vocabDue\}/)
})

test("review banners prioritize above-the-fold state artwork with bounded sizes", () => {
  const source = read("src/components/review/review-banners.tsx")

  assert.match(source, /src="\/assets\/states\/state-empty\.webp"[\s\S]*?sizes="\(max-width: 640px\) 160px, 192px"[\s\S]*?priority/)
  assert.match(source, /src="\/assets\/review\/review-streak\.webp"[\s\S]*?sizes="\(max-width: 896px\) 100vw, 896px"[\s\S]*?priority/)
  assert.doesNotMatch(source, /src="\/assets\/review\/review-streak\.webp"[\s\S]{0,180}sizes="100vw"/)
})

test("ReviewDeckCard owns deck counts and start action presentation", () => {
  const source = read("src/components/review/review-deck-card.tsx")

  assert.match(source, /export function ReviewDeckCard/)
  assert.match(source, /formatReviewDueCount/)
  assert.match(source, /startTestId\?: string/)
  assert.match(source, /data-testid=\{startTestId\}/)
  assert.match(source, /待复习/)
  assert.match(source, /已加入/)
  assert.match(source, /disabled=\{startDisabled\}/)
  assert.match(source, /\{extra \? <div className="pt-1">\{extra\}<\/div> : null\}/)
})

test("RecentMistakes owns recent mistake preview and remove action", () => {
  const source = read("src/components/review/recent-mistakes.tsx")

  assert.match(source, /export function RecentMistakes/)
  assert.match(source, /data-testid="recent-mistakes"/)
  assert.match(source, /data-testid=\{`recent-mistake-\$\{mistake\.id\}`\}/)
  assert.match(source, /mistakes\.slice\(0, 6\)\.map/)
  assert.match(source, /mistake\.questionText \?\? mistake\.questionAudio/)
  assert.match(source, /onRemove\(mistake\.id\)/)
  assert.match(source, /点击“错题本”开始复习/)
})
