import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import test from "node:test"

const root = path.resolve(import.meta.dirname, "..", "..")

function read(relPath) {
  return fs.readFileSync(path.join(root, relPath), "utf8")
}

test("review runner delegates today deck sessions to TodayReviewSession", () => {
  const runner = read("src/components/review/review-runner.tsx")

  assert.match(runner, /import dynamic from "next\/dynamic"/)
  assert.match(runner, /import\("@\/components\/review\/today-review-session"\)/)
  assert.match(runner, /const TodayReviewSession = dynamic\(/)
  assert.match(runner, /<TodayReviewSession/)
  assert.match(runner, /remainingDueAfterBatch=\{remainingDueAfterBatch\}/)
  assert.match(runner, /kanaSrs=\{kanaSrs\}/)
  assert.match(runner, /vocabSrs=\{vocabSrs\}/)
  assert.match(runner, /mistakeSrs=\{mistakeSrs\}/)
  assert.doesNotMatch(runner, /makeKanaReviewQuestion/)
  assert.doesNotMatch(runner, /makeVocabReviewQuestion/)
  assert.doesNotMatch(runner, /mistakeToQuestion\(item\)/)
  assert.doesNotMatch(runner, /useVocabularyReviewPool/)
})

test("TodayReviewSession delegates mixed queue data, shared prompts, and SRS deck grading", () => {
  const source = read("src/components/review/today-review-session.tsx")

  assert.match(source, /export function TodayReviewSession/)
  assert.match(source, /remainingDueAfterBatch: number/)
  assert.match(source, /getTodayReviewBatchCompletionTitle\(remainingDueAfterBatch\)/)
  assert.match(source, /useReviewSessionState\(items\)/)
  assert.match(source, /const \{ dropCurrent \} = review/)
  assert.match(source, /const vocabIds = useMemo/)
  assert.match(source, /useVocabularyReviewPool\(vocabIds, vocabIds\.length > 0\)/)
  assert.match(source, /from "@\/lib\/today-review-session"/)
  assert.match(source, /getTodayReviewItemKey\(current\)/)
  assert.match(source, /resolveTodayReviewItemData\(\{/)
  assert.match(source, /current,\s+vocabulary: vocabulary\.data,\s+mistakes: notebook\.byId,/)
  assert.match(source, /canRecordTodayReviewItem\(current/)
  assert.match(source, /gradeTodayReviewItem\(current, result/)
  assert.match(source, /ReviewEmptyQuestionState/)
  assert.match(source, /ReviewErrorState/)
  assert.match(source, /if \(vocabulary\.error\)/)
  assert.match(source, /onRetry=\{vocabulary\.retry\}/)
  assert.match(source, /今日复习题库加载失败/)
  assert.match(source, /const \{ data, missingReviewEntry, insufficientQuestionOptions \} = useMemo/)
  assert.doesNotMatch(source, /const kanaItem = useMemo/)
  assert.doesNotMatch(source, /const vocabItem = useMemo/)
  assert.doesNotMatch(source, /const kanaQuestion = useMemo/)
  assert.doesNotMatch(source, /const vocabQuestion = useMemo/)
  assert.doesNotMatch(source, /makeKanaReviewQuestion/)
  assert.doesNotMatch(source, /makeVocabReviewQuestion/)
  assert.doesNotMatch(source, /makeVocabReviewQuestion\(vocabItem\.id, vocabulary\.data\)/)
  assert.doesNotMatch(source, /mistakeToQuestion/)
  assert.match(source, /if \(current\.deck === "vocab" && \(vocabulary\.loading \|\| vocabulary\.error\)\) return/)
  assert.match(source, /if \(missingReviewEntry\) \{/)
  assert.match(source, /dropCurrent\(\)/)
  assert.match(source, /if \(insufficientQuestionOptions\)/)
  assert.match(source, /当前假名复习题不足/)
  assert.match(source, /当前单词复习题不足/)
  assert.match(source, /return null/)
  assert.match(source, /<MixedReviewPrompt\b/)
  assert.match(source, /<ReviewAnswerFeedback/)
  assert.match(source, /correct=\{review\.lastAnswerCorrect\}/)
  assert.match(source, /showSelectedAnswer/)
  assert.match(source, /showSpecialFeedback=\{shouldShowReviewSpecialFeedback\(data\.question\.type\)\}/)
  assert.doesNotMatch(source, /return kanaSrs\.has\(current\.id\)/)
  assert.doesNotMatch(source, /return vocabSrs\.has\(current\.id\)/)
  assert.doesNotMatch(source, /return mistakeSrs\.has\(current\.id\)/)
  assert.doesNotMatch(source, /return kanaSrs\.gradeExisting\(current\.id/)
  assert.doesNotMatch(source, /return vocabSrs\.gradeExisting\(current\.id/)
  assert.doesNotMatch(source, /return mistakeSrs\.gradeExisting\(current\.id, "good"\)/)
  assert.doesNotMatch(source, /const currentKey = current \? `\$\{current\.deck\}:\$\{current\.id\}` : null/)
  assert.match(source, /const saveError = !!currentKey && saveErrorKey === currentKey/)
  assert.match(source, /setSaveErrorKey\(recorded \? null : currentKey\)/)
  assert.match(source, /<PracticeSaveError show=\{saveError\} \/>/)
  assert.match(source, /data-testid="review-remaining"/)
})

test("today review session pure adapter owns mixed deck resolution and grading rules", () => {
  const source = read("src/lib/today-review-session.ts")

  assert.match(source, /export function resolveTodayReviewItemData/)
  assert.match(source, /export function canRecordTodayReviewItem/)
  assert.match(source, /export function gradeTodayReviewItem/)
  assert.match(source, /export function getTodayReviewBatchCompletionTitle/)
  assert.match(source, /makeKanaReviewQuestion/)
  assert.match(source, /makeVocabReviewQuestion/)
  assert.match(source, /mistakeToQuestion/)
  assert.match(source, /if \(current\.deck === "mistakes"\) \{/)
  assert.match(source, /if \(!result\.correct\) return true/)
})
